In [6]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [7]:
# Q1. Is there any difference in the data type of variables list_ and array_list? 
#     If there is then write a code to print the data types of both the variables.
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
print(list_)
print(array_list)

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


In [8]:
# Q2. Write a code to print the data type of each & every element of
#     both the variables list_ & arra_list.

print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [9]:
"""
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, 
list_ and arra_list? 
If so then print the data types of each and every element present in both the 
variables, list_and arra_list.
"""

# The elements in array_list will have the data type int, 
# while the elements in list_ will still have the data type str.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
# Q4. To find the shape and size of the variable num_array, you can use the following code:
shape = num_array.shape
size = num_array.size

print("Shape:", shape)
print("Size:", size)


Shape: (2, 3)
Size: 6


In [12]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#     creation function.
zero_array = np.zeros((3, 3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
identity_matrix = np.eye(5)