In [83]:
# To work on arrays and matrices 

In [84]:
import numpy as np

In [85]:
l=[1,2,3,4,5]
arr=np.array(l)

In [86]:
type(arr)

numpy.ndarray

In [87]:
array_2d=np.array([[1,2],[3,4]])
array_2d

array([[1, 2],
       [3, 4]])

In [88]:
array_2d[0][0]

1

In [89]:
# 3 ways to convert list into array 

a=[1,2,3,4,5]
array1=np.array(a)
array2=np.asanyarray(a)
array3=np.asarray(a)

In [90]:
# Matrix is always 2D array
# Matrix is a subclass or array 
b=np.matrix([1,2,3,45])
b

matrix([[ 1,  2,  3, 45]])

In [91]:
# You are copying the address 
# Swollow copy 

l=[1,2,3,4,5]
a=np.array(l)
c=a
print(c)
print(a)
c[0]=100
print(c)
print(a)


a[0]


[1 2 3 4 5]
[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]


100

In [92]:
l=[1,2,3,4,5,6,7,8]
a=np.array(l)
c=a.copy()
c[3]=100
print(c)
print(a)

[  1   2   3 100   5   6   7   8]
[1 2 3 4 5 6 7 8]


In [93]:
# Make a 3 x 3 matrix
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [94]:
# Make a 3 x 3 matrix
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [95]:
itterable =(i *i  for i in range (5))
np.fromiter(itterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [96]:
# Give a string and get array 
np.fromstring('123 456',sep=' ') # Space is the seprator 

array([123., 456.])

In [101]:
# Data types under numpy 
l=[1,2,3,4,5,6,7,8,9]
array1=np.array(l)
print(array1)
print("Dimension : ", array1.ndim)
print("Size: ", array1.size)
print("Sgape: ",array1.shape)
print(array1.dtype)
print("##################################################################")



l=[[1,2,3,4],[2,3,4,5]]
array1=np.array(l)
print(array1)
print("Dimension : ", array1.ndim)
print("Size: ", array1.size)
print(array1.dtype)
print("Sgape: ",array1.shape) ########### 2 rows, 4 column
print("##################################################################")


[1 2 3 4 5 6 7 8 9]
Dimension :  1
Size:  9
Sgape:  (9,)
int64
##################################################################
[[1 2 3 4]
 [2 3 4 5]]
Dimension :  2
Size:  8
int64
Sgape:  (2, 4)
##################################################################


In [ ]:
# You can store complex data, string, float in an array 

In [106]:
list(range(0,5))
try:
    list(range(0.2,5))
except:
    print ("Range cqan take only interger")
    
np.arange(2.3,4,0.1)

Range cqan take only interger


array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9])

In [109]:
# Make a line from 1 to 5 and then produce 10 points in between 
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [118]:
print("1 D Matrix")
# Make a zero matrix 
print(np.zeros(3))
print("##################################"+'\n2 D Matrix')
# 3 rows, 4 column 
print(np.zeros((3,4)))
print("##################################"+'\n3 D Matrix')
# 3 matrices of 4x2
print(np.zeros((3,4,2)))

1 D Matrix
[0. 0. 0.]
##################################
2 D Matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
##################################
3 D Matrix
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [119]:
### Ones Matrix 


print("1 D Matrix")
# Make a zero matrix 
print(np.ones(3))
print("##################################"+'\n2 D Matrix')
# 3 rows, 4 column 
print(np.ones((3,4)))
print("##################################"+'\n3 D Matrix')
# 3 matrices of 4x2
print(np.ones((3,4,2)))

1 D Matrix
[1. 1. 1.]
##################################
2 D Matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
##################################
3 D Matrix
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [120]:
# Scallar product 
print(np.ones((3,4))*4)


[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [127]:
# Create a empty array, 
# Array with very small values 
np.empty((3,1))




array([[7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304]])

In [128]:
# Identity matrix 
# Its always square matrix 
# Determinant is 1 


np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [129]:
# Produce 20 data between 2,3
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [131]:
# Produce 20 data between 2,3
np.logspace(2,4,20, base = 4)

array([ 16.        ,  18.5137638 ,  21.42246562,  24.78815428,
        28.68262708,  33.18896142,  38.40328703,  44.43683656,
        51.4183185 ,  59.49666272,  68.84419752,  79.66032573,
        92.1757784 , 106.65753682, 123.41452774, 142.80421347,
       165.24021734, 191.20114709, 221.24080468, 256.        ])

In [133]:
# To generate a random number 
# It generates the data whoes mean is zero always  and standard normal distribution is 0
arr=np.random.randn(3,4)
import pandas as pd 
pd.DataFrame(arr)

0         1         2         3
0  0.622926  0.155620  0.461814  0.082292
1 -0.272519  0.048033  0.391447 -0.824584
2  0.322312 -0.184301  1.203033  0.568115

In [135]:
# To generate a random number 
arr=np.random.rand(3,4)
import pandas as pd 
pd.DataFrame(arr)

0         1         2         3
0  0.977625  0.813572  0.680414  0.185309
1  0.637251  0.846012  0.913277  0.780946
2  0.457231  0.809549  0.967663  0.866412

In [139]:
# To generate a random int 
# Limits followed by number of numbers you want 
arr=np.random.randint(3,9,5)
arr

array([7, 3, 5, 6, 6])

In [143]:
# Put random numbers in a 2D Matrix of 3x4
import pandas as pd
print(np.random.randint(1,10,(3,4)))
print("Data")
print(pd.DataFrame(np.random.randint(1,10,(3,4))))

[[5 7 1 6]
 [4 8 9 5]
 [9 4 1 3]]
Data
   0  1  2  3
0  4  8  9  7
1  7  8  4  5
2  3  3  7  7


In [145]:
# Re shape 
arr= np.random.randint(1,10,(3,4))
arr.resize((2,6))
arr

array([[7, 9, 6, 9, 2, 9],
       [9, 1, 9, 8, 4, 4]])

In [151]:
# Now you do not need to give always the correct input while reshaping 
# If number of rows is two the column has to be 6
arr= np.random.randint(1,10,(3,4))
arr.resize((2,33472))
arr

array([[7, 7, 6, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [156]:
# Slicing in an array 
print(arr[0][1])
print(arr[0][2:5])

7
[6 6 7]


In [174]:
# You check weather 
array=np.random.randint(1,100,(5,5))
print(array>50)  # given data is above 50

print("\n\n\nNumber above 50")
print(array[array>50])

[[ True  True  True  True  True]
 [False  True False  True  True]
 [ True  True False  True False]
 [False False False False False]
 [ True False  True False False]]



Number above 50
[60 96 66 90 64 74 92 89 60 67 96 98 53]


In [175]:
print(array)
# Print only a sub-section of data 
print("Check\n\n")
array[2:4, [1,2]]

[[60 96 66 90 64]
 [13 74 30 92 89]
 [60 67 10 96 20]
 [42 21 19  9 23]
 [98 15 53 41 46]]
Check




array([[67, 10],
       [21, 19]])

In [176]:
print(array)
print("You can manipulate any given data at any point easily ")
array[0][0]=0
print(array)

[[60 96 66 90 64]
 [13 74 30 92 89]
 [60 67 10 96 20]
 [42 21 19  9 23]
 [98 15 53 41 46]]
You can manipulate any given data at any point easily 
[[ 0 96 66 90 64]
 [13 74 30 92 89]
 [60 67 10 96 20]
 [42 21 19  9 23]
 [98 15 53 41 46]]


In [179]:
# One to One maping and calculate 

arr1=np.random.randint(1,3,(3,4))
arr2=np.random.randint(1,3,(3,4))

print (arr1+ arr2)
print(arr1-arr2)
print(arr1*arr2) # One to one index multiplication 

[[3 4 3 4]
 [4 3 3 4]
 [3 4 3 3]]
[[-1  0 -1  0]
 [ 0 -1 -1  0]
 [-1  0  1 -1]]
[[2 4 2 4]
 [4 2 2 4]
 [2 4 2 2]]


In [185]:
# Matrix multiplicatiuon 
"""
m x n = p x q

only when n= p
The answer will be m x q
"""
array1=np.array([[2,2,1],[2,1,2],[1,2,1]])
array2=np.array([[1,2,2],[2,1,1],[1,1,1]])

print(array1@array2)

[[7 7 7]
 [6 7 7]
 [6 5 5]]


In [187]:
# Divide each element by 0
print(array/0)

# Add 100 to each element
print(array+100)

print(array**2)

[[nan inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]
[[100 196 166 190 164]
 [113 174 130 192 189]
 [160 167 110 196 120]
 [142 121 119 109 123]
 [198 115 153 141 146]]
[[   0 9216 4356 8100 4096]
 [ 169 5476  900 8464 7921]
 [3600 4489  100 9216  400]
 [1764  441  361   81  529]
 [9604  225 2809 1681 2116]]


/tmp/ipykernel_3752/1407089548.py:2: RuntimeWarning: divide by zero encountered in divide
  print(array/0)
/tmp/ipykernel_3752/1407089548.py:2: RuntimeWarning: invalid value encountered in divide
  print(array/0)


In [190]:
# Broadcasting in numpy 
x=np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [191]:
row=np.array([1,2,3,4])

In [194]:
# Broadcasting row by row again ana dagain 
row + x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [200]:
# 1 D array cant be transposed 
row.T

col=np.array([[1,2,3,4]])
col=col.T
col + x

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [203]:
c=np.random.randint(1,4,(3,4))
print(np.sqrt(c))
print(np.exp(c))
np.log10(c)

[[1.73205081 1.         1.41421356 1.        ]
 [1.         1.         1.41421356 1.73205081]
 [1.73205081 1.41421356 1.41421356 1.73205081]]
[[20.08553692  2.71828183  7.3890561   2.71828183]
 [ 2.71828183  2.71828183  7.3890561  20.08553692]
 [20.08553692  7.3890561   7.3890561  20.08553692]]


array([[0.47712125, 0.        , 0.30103   , 0.        ],
       [0.        , 0.        , 0.30103   , 0.47712125],
       [0.47712125, 0.30103   , 0.30103   , 0.47712125]])