In [26]:
# Sorting 
import numpy as np
array= np.random.randint(1,10,7)
print("OG array ",array)
print("Sorted Array ",np.sort(array))

OG array  [8 5 6 8 8 1 5]
Sorted Array  [1 5 5 6 8 8 8]


In [27]:
# At what location should we enter 5
array= np.random.randint(1,10,7)
print('OG array ',array)
print('5 should be entered at ', np.searchsorted(array,5),'location')

OG array  [7 5 2 4 9 7 2]
5 should be entered at  4 location


In [28]:
# FInd out what all non zero data we have in the given data
array1=np.array([1,2,3,4,6,0,2,3,0,0,2,3,0])
print('Total number of non zero data ',np.count_nonzero(array1))

Total number of non zero data  9


In [29]:
# Data greater than 6
array= np.random.randint(1,10,7)
print('Orignal Array ',array)
print("Number greater than 6 is at what location  ",np.where(array > 6))


Orignal Array  [3 4 5 5 7 4 5]
Number greater than 6 is at what location   (array([4]),)


In [30]:
# Extract data from array 
# Data greater than 6
array= np.random.randint(1,10,7)
print('Orignal Array ',array)
print("Number greater than 6 is   ",np.extract(array > 6,array))

Orignal Array  [9 6 5 6 6 5 2]
Number greater than 6 is    [9]


In [31]:
# Give byte representation of dat 
array= np.random.randint(1,10,7)
print("Byte representation\n",array.byteswap())

Byte representation
 [432345564227567616 360287970189639680 504403158265495552
 504403158265495552 432345564227567616  72057594037927936
 504403158265495552]


In [36]:
# Copy and view


# Deep COpy
a=np.copy(array)
a[0]=0
print("Orignal array ",array)
print('Copy ',a)
print('\n\n\n\n')
#shallow copy
b=array.view()
b[0]=100
print("Orignal array ",array)
print('Copy ',b)

Orignal array  [100   5   7   7   6   1   7]
Copy  [0 5 7 7 6 1 7]





Orignal array  [100   5   7   7   6   1   7]
Copy  [100   5   7   7   6   1   7]


In [40]:
import numpy.matlib as ma
# What all you did in numpy, you can do in matrix
print(ma.ones(4))
print(ma.zeros((3,4)))

[[1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
# Linear algebra 
array1= np.random.randint(1,10,(2,2))
array2= np.random.randint(1,10,(2,2))

print("Array 1\n",array1)
print("Array 2\n",array2)
print(np.dot(array1,array2))


########## This is same as 
array1 @ array2

Array 1
 [[5 8]
 [6 9]]
Array 2
 [[7 4]
 [5 6]]
[[75 68]
 [87 78]]


array([[75, 68],
       [87, 78]])