In [1]:
import numpy as np
array= np.random.randint(1,10,(3,4))
print("OG array")
print(array)


print('\n\n'+'Reshape')
print(array.reshape(2,6))

print('\n\n'+ "Transpose")
print(array.T)


print('\n\nArray Array is flatten')
print(array.flatten())

OG array
[[1 3 4 5]
 [3 1 4 9]
 [8 1 4 6]]


Reshape
[[1 3 4 5 3 1]
 [4 9 8 1 4 6]]


Transpose
[[1 3 8]
 [3 1 1]
 [4 4 4]
 [5 9 6]]


Array Array is flatten
[1 3 4 5 3 1 4 9 8 1 4 6]


In [2]:
array1=np.array([1,2,3,4])
print(array1)
print("Dimension: ",array1.ndim)

[1 2 3 4]
Dimension:  1


In [3]:
# Expand the rows into column 
print(np.expand_dims(array1,axis=1))
print("Dimension: ",np.expand_dims(array1,axis=1).ndim)

print("###########################################################")
# Expand the rows into column 
print(np.expand_dims(array1,axis=0))
print("Dimension: ",np.expand_dims(array1,axis=1).ndim)

[[1]
 [2]
 [3]
 [4]]
Dimension:  2
###########################################################
[[1 2 3 4]]
Dimension:  2


In [7]:
arr=np.random.randint(1,10,(4,4))
print(arr)
print("@@@@@@@@@@@@@@@@@@@@@@@@")
print(np.squeeze(arr))

[[5 2 9 9]
 [2 2 3 5]
 [9 4 4 7]
 [1 3 5 7]]
@@@@@@@@@@@@@@@@@@@@@@@@
[[5 2 9 9]
 [2 2 3 5]
 [9 4 4 7]
 [1 3 5 7]]


In [8]:
# Now squeeze will work
data=np.array([[1],[2],[3]])
np.squeeze(data)

array([1, 2, 3])

In [10]:
# Repeat 
np.repeat(arr,3)

array([5, 5, 5, 2, 2, 2, 9, 9, 9, 9, 9, 9, 2, 2, 2, 2, 2, 2, 3, 3, 3, 5,
       5, 5, 9, 9, 9, 4, 4, 4, 4, 4, 4, 7, 7, 7, 1, 1, 1, 3, 3, 3, 5, 5,
       5, 7, 7, 7])

In [13]:
# Roll 
arr1=np.random.randint(1,10,4)
print(arr1)
print(np.roll(arr1,1))

[8 4 2 7]
[7 8 4 2]


In [19]:
# Convert into diagnoal 

# Roll 
arr1=np.random.randint(1,10,4)
print('OG array ',arr1,'\n\n')
print(np.diag(arr1))

OG array  [5 5 9 3] 


[[5 0 0 0]
 [0 5 0 0]
 [0 0 9 0]
 [0 0 0 3]]


In [22]:
# You can perform Binarry opperations like addition, subtraction, multiplication, Or, And in , Greater than
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

print("Array 1\n",arr1)
print("Array 1\n",arr2)

print("Addition ")
print(arr1+arr2)

print("Multiplication")
print(arr1*arr2)

print("Sub ")
print(arr1-arr2)

print("Division")
print(arr1/arr2)

print("Mod ")
print(arr1%arr2)

print("Int div")
print(arr1//arr2)

print("And ")
print(arr1&arr2)

print("OR")
print(arr1|arr2)

print("NOT ")
print(~arr1)

print("Greater than ")
print(arr1>arr2)

Array 1
 [[9 8 3 1]
 [8 9 7 5]
 [1 4 6 8]]
Array 1
 [[1 1 7 9]
 [7 5 5 3]
 [4 2 5 7]]
Addition 
[[10  9 10 10]
 [15 14 12  8]
 [ 5  6 11 15]]
Multiplication
[[ 9  8 21  9]
 [56 45 35 15]
 [ 4  8 30 56]]
Sub 
[[ 8  7 -4 -8]
 [ 1  4  2  2]
 [-3  2  1  1]]
Division
[[9.         8.         0.42857143 0.11111111]
 [1.14285714 1.8        1.4        1.66666667]
 [0.25       2.         1.2        1.14285714]]
Mod 
[[0 0 3 1]
 [1 4 2 2]
 [1 0 1 1]]
Int div
[[9 8 0 0]
 [1 1 1 1]
 [0 2 1 1]]
And 
[[1 0 3 1]
 [0 1 5 1]
 [0 0 4 0]]
OR
[[ 9  9  7  9]
 [15 13  7  7]
 [ 5  6  7 15]]
NOT 
[[-10  -9  -4  -2]
 [ -9 -10  -8  -6]
 [ -2  -5  -7  -9]]
Greater than 
[[ True  True False False]
 [ True  True  True  True]
 [False  True  True  True]]


In [26]:
arr=np.array(['sujeet a ','Amberkar'])
print("OG array ",arr)
print("Upper case ",np.char.upper(arr))
print("Title style ",np.char.title(arr))
print("Capitalize ",np.char.capitalize(arr))

OG array  ['sujeet a ' 'Amberkar']
Upper case  ['SUJEET A ' 'AMBERKAR']
Title style  ['Sujeet A ' 'Amberkar']
Capitalize  ['Sujeet a ' 'Amberkar']


In [34]:
# Trignometric values
arr = np.random.randint(1,10 , (3,4))
print("Sine\n",np.sin(arr))
print("Cos\n",np.cos(arr))
print("Tan\n",np.tan(arr))
print("Mean",np.mean(arr))
print("Max\n",np.max(arr))
print("log\n",np.log(arr))

Sine
 [[ 0.14112001 -0.2794155   0.14112001  0.6569866 ]
 [ 0.41211849  0.98935825 -0.7568025  -0.7568025 ]
 [ 0.41211849  0.98935825  0.14112001  0.84147098]]
Cos
 [[-0.9899925   0.96017029 -0.9899925   0.75390225]
 [-0.91113026 -0.14550003 -0.65364362 -0.65364362]
 [-0.91113026 -0.14550003 -0.9899925   0.54030231]]
Tan
 [[-0.14254654 -0.29100619 -0.14254654  0.87144798]
 [-0.45231566 -6.79971146  1.15782128  1.15782128]
 [-0.45231566 -6.79971146 -0.14254654  1.55740772]]
Mean 5.416666666666667
Max
 9
log
 [[1.09861229 1.79175947 1.09861229 1.94591015]
 [2.19722458 2.07944154 1.38629436 1.38629436]
 [2.19722458 2.07944154 1.09861229 0.        ]]
